### ISSUE TITLE
404 error fetching coins icons

### ISSUE THREAD

**Issue by sawine** [influenceink/inklabs-interface#217]
![image](https://user-images.githubusercontent.com/1281459/192906661-f9fa8f71-cc76-41d7-91c8-89ffb4bb81c8.png)

**Comment by IntelMin** [comment]
Fetch icons from Trustwallet Github assets.
Trustwallet has almost all valuable tokens, so there must be icons of top coins we are going to adopt.

Here's an example url.
[USDC icon](https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png)

This url generation could be the second option when it fails to fetch from Uniswap.

**Comment by IntelMin** [comment]
It is proved that if a coin logo does not exist on Uniswap, it does not exist on Trustwallet as well.
We might ignore this issue since the same 404 error exists on Uniswap App too.

**Comment by sawine** [comment]
coingecko api?
