### ISSUE TITLE
Menu overlay issue on mobile

### ISSUE THREAD

**Issue by sawine** [influenceink/inklabs-interface#223]
On mobile, the menu is overlapping elements,  make sure it is always at the bottom with black behind

![image](https://user-images.githubusercontent.com/1281459/192907812-49e6d2b3-47b4-4e9a-8480-5690a7021399.png)

![image](https://user-images.githubusercontent.com/1281459/192907832-55628389-affb-4036-adbd-173662d86a7e.png)

**Comment by zKnight223** [comment]
done
