### ISSUE TITLE
text fixes

### ISSUE THREAD

**Issue by sawine** [influenceink/inklabs-interface#257]
![image](https://user-images.githubusercontent.com/1281459/193639720-9ef6c669-868e-4ab0-8ce6-eab8f9d89019.png)

Should say "every digital parcel maps to an actual location"

![image](https://user-images.githubusercontent.com/1281459/193639786-47641f3d-4b4c-45c6-851c-977a597b3e5c.png)

"Our team is constantly exploring new opportunities to..."

**Comment by zKnight223** [comment]
done
