### ISSUE TITLE
Ink token page adjustments

### ISSUE THREAD

**Issue by sawine** [influenceink/inklabs-interface#258]
Change to look like this this:

![image](https://user-images.githubusercontent.com/1281459/193641495-2a23ba42-a4b3-405d-9ea1-b74a8f981f7b.png)

Kill current "private rd 1" card
Rename current Private Rd 2 "Private Presale"
Under "Private Presale", kill "institutional"
The text under "19 months vest" isn't quite readable.  i think "of total supply" should also be bigger

.css-tx0d9a {
padding-top: 4px;
font-size: 8px;
line-height:8px;
}

.css-1d0gwmp {
padding-right: 0px;
font-size: 8px;
}

**Comment by zKnight223** [comment]
done
