### ISSUE TITLE
Make minimum transaction 5$ on mainnets

### ISSUE THREAD

**Issue by sawine** [influenceink/inklabs-interface#270]
I cant test on eth and matic main nets because frontend has 5000 minium.

Please make 5$ limit for testing on main net.
Thanks

**Comment by zKnight223** [comment]
done

**Comment by sawine** [comment]
Did you only change it on polygon or also on ETH?

Only seem to be able to send transaction on polygon...

I tried to send WMATIC but its been pending for 10min, not sure if something is wrong. Will try to do more tests.
