### ISSUE TITLE
Terms checkbox location and link

### ISSUE THREAD

**Issue by sawine** [influenceink/inklabs-interface#303]
![image](https://user-images.githubusercontent.com/1281459/200391438-b033d536-a732-44ff-a341-8c2dce5b72a8.png)

The "accept terms" checkbox should be on the token swap page and not on the login page.

The "terms" should be underlined and open the terms page in a new window.

**Comment by IntelMin** [comment]
According to #298 , it should be on the register page.
![image](https://user-images.githubusercontent.com/76229434/200864931-992e5b48-86df-4d45-b71f-a95c2f077be8.png)
Is this requirement changed?

**Comment by sawine** [comment]
Yes its changed,  its because he changed his mind after sending me the screenshot. So it goes on the swap page

**Comment by IntelMin** [comment]
Fixed.
