### ISSUE TITLE
Add image button to menu

### ISSUE THREAD

**Issue by sawine** [influenceink/inklabs-interface#304]
Add this image:
![CTA-20%](https://user-images.githubusercontent.com/1281459/200410505-9f706581-5651-4f8d-b8e3-6145cba95d40.png)

In the menu like so:

![image (230)](https://user-images.githubusercontent.com/1281459/200410529-5559cdab-45c3-4690-b8d8-94b0d8cf2e0f.png)

**Comment by sawine** [comment]
The URL for the link will be added later...

**Comment by IntelMin** [comment]
Added the image button. Waiting for the link...

**Comment by sawine** [comment]
They will send the link later, they want to add button first....
