### ISSUE TITLE
Remove and replace bottom buttons

### ISSUE THREAD

**Issue by sawine** [influenceink/inklabs-interface#305]
Remove these 2 buttons:

![image](https://user-images.githubusercontent.com/1281459/200410945-7b90dfef-9401-48e1-b4bc-1c72fdbe8752.png)

Add button in the corner instead:
![reservenowbutton](https://user-images.githubusercontent.com/1281459/200411028-e0b3080e-d639-4062-a85c-27d64e284657.png)

Like so:

![image (231)](https://user-images.githubusercontent.com/1281459/200411053-b5fe9cde-4c46-42c0-b1a8-7348e7d02677.png)

**Comment by IntelMin** [comment]
What about mobile design with this button?

**Comment by IntelMin** [comment]
Fixed.
