### ISSUE TITLE
Update Vision page

### ISSUE THREAD

**Issue by sawine** [influenceink/inklabs-interface#306]
Add bottom 3 sections:

![image](https://user-images.githubusercontent.com/1281459/200411275-e97aaaa9-a100-4f62-b31b-26ea761ae711.png)

Images:
![raodmap2](https://user-images.githubusercontent.com/1281459/200411359-ee271b88-a30c-4f04-afe2-539ecc3e8037.png)
![raodmap3](https://user-images.githubusercontent.com/1281459/200411360-f2e9bc30-b5b9-401b-8cab-03a0fb893623.png)
![roadmap1](https://user-images.githubusercontent.com/1281459/200411362-068c9a9d-f49e-4ce8-9b88-02a0fff8bdfe.png)

**Comment by IntelMin** [comment]
Fixed.
