### ISSUE TITLE
Add bonus ink on profile

### ISSUE THREAD

**Issue by sawine** [influenceink/inklabs-interface#314]
![image](https://user-images.githubusercontent.com/1281459/201775348-bc050704-dca4-4b99-8a21-8fe46dc8d3c8.png)

Kris is currently adding new API variable;   bonus ink.

To be displayed next to ink reserved.     change "total ink reserved" for "INK token reserved"   and the 2nd one "INK token bonus"

Also hide the showall button if there are no zip

**Comment by sawine** [comment]
if you have no zip, replace button with "You have no zip codes"

**Comment by IntelMin** [comment]
done
